# -*- coding: utf-8 -*-
"""scalars_2515061026 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HK79iJ7dq4fb40tPALGhh_teLhRDybsU
"""

import numpy as np

# buat variabel skalar x dan simpan suatu nilai skalar
x = 26
x

# tipe dari x
type(x)

# buat variabel skalar y
y = 26

# tipe data dari y
type(py_sum)

# menjumalhkan variabel x + y
py_sum = x + y
py_sum

# buat variabel bernama x_float dan simpan suatu nilai desimal
x_float = 26.0
float_sum = x_float + y # jumlahkan x_float dengan y
float_sum

# tipe data dari x float
type(float_sum)

import tensorflow as tf

# buat variabel x dan simpan dan simpan suatau nilai skalar
x_tf = tf.Variable(26, dtype=tf.int16) # dtype is optional
x_tf

x_tf.shape

y_tf = tf.Variable(26, dtype=tf.int16 )
y_tf

x_tf + y_tf

tf_sum = tf.add(x_tf, y_tf)
tf_sum

tf_sum.numpy()

type(tf_sum.numpy())

tf_float = tf.Variable(25., dtype=tf.float16)
tf_float

import torch

# buat variabel skalar x pada troch
x_pt = torch.tensor(26)
x_pt

x_pt.shape